version: "3.5"
services:
  be-template:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: be-template
    environment:
      PROFILE: local
      DB_HOST: mysql-template
      DB_PORT: 3306
      DB_NAME: db_greeting
      DB_USERNAME: mysql_user
      DB_PASSWORD: mysql_pw
      AUTH0_AUDIENCE: https://lpe.integration.com
      AUTH0_ISSUER_URI: https://dev-yrwmvzo0.us.auth0.com/
    ports:
      - "3000:3000"
    networks:
      - lightweight_network
  mysql:
    image: mysql:8.0.20
    container_name: mysql-template
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_greeting
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pw
    ports:
      - "3306:3306"
    networks:
      - lightweight_network

networks:
  lightweight_network:
    name: lightweight-network